spring:
  name: test
  activate:
    on-profile: test
  datasource:
    platform: h2
    url: jdbc:h2:mem:clientsDB;DATABASE_TO_LOWER=TRUE
    username: testUser
    password: testUser
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    changelog: classpath:/db/master-changelog.xml
    contexts: test
  jpa:
    show-sql: true